name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies and LLD
      run: |
        sudo apt-get update
        sudo apt-get install -y lld
    - name: make
      run: make

  regression:

    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run regression tests
      run: ./tests/run_tests.sh