name: Tests CI

on:
  workflow_run:
    workflows: ["C/C++ CI"]
    types:
      - completed

jobs:
  regression-tests:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    - name: Go to tests directory
      run: cd tests
    - name: Run tests
      run: ./run_tests.sh
